name: Build and test B-branch.

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dotnet dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore

      - name: Run Unit-Test
        working-directory: ./tests/UnitTests/
        run: dotnet test --no-build --verbosity detailed

      - name: Build Docker Integration-Test Image
        run: docker build -t integration-tests .

      - name: Run Docker Integration-Tests Container
        run: docker run --rm integration-tests
