name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Unit-Test
        working-directory: ./tests/UnitTests/
        run: dotnet test --no-build --verbosity detailed

      - name: Build Docker image
        run: docker build -t integration-tests .

      - name: Run Docker Integration Tests
        run: docker run --rm integration-tests
